name: medigo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images/
  #   - assets/images/doctor/
  #   - assets/images/icones/
  #   - assets/images/logo/
  #   - assets/images/speciality/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter_Regular.ttf
  #       - asset: assets/fonts/Inter_Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter_SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter_Bold.ttf
  #         weight: 700

flutter_assets:
  assets_path: assets/images
  output_path: lib/core/constant/
  filename: app_image.dart
  field_prefix: null
  ignore_comments: true
  classname: AppImage
