name: medigo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  another_xlider: ^3.0.2
  cupertino_icons: ^1.0.8
  easy_date_timeline: ^2.0.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.3
  get: ^4.7.3
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/doctor/
    - assets/images/icones/
    - assets/images/logo/
    - assets/images/speciality/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_Regular.ttf
        - asset: assets/fonts/Inter_Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_Bold.ttf
          weight: 700

flutter_assets:
  assets_path: assets/images
  output_path: lib/core/constant/
  filename: app_image.dart
  field_prefix: null
  ignore_comments: true
  classname: AppImage
